Repository kubevirt/libguestfs-appliance, pull requests merged in 2021-05, with the labels that each got.

#3 Set version on the libguestfs-appliance
  Dockerfile
Labels: approved, dco-signoff: yes, lgtm, size/XS

#5 Use the same fedora version as the images used by kubevirt
  Dockerfile
Labels: approved, dco-signoff: yes, size/XS

#4 owners: Add myself as reviewer and approver
  OWNERS
Labels: approved, dco-signoff: yes, do-not-merge/invalid-owners-file, lgtm, needs-ok-to-test, size/XS
